on:
  push:
    branches:
      - main
      - development
jobs:
  wait-for-approval:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment: prod
    steps:
      - name: Approve deployment
        run: echo "Deployment approved"

  build-deploy:
    # Add needs condition only for main branch
    needs: [wait-for-approval]
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/development'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: ['function1', 'function2']
        environment:
          - ${{ (github.ref == 'refs/heads/main' && 'prod') || (github.ref == 'refs/heads/development' && 'dev') }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      # Calculate hash of SAM application files
      - name: Calculate SAM app hash
        id: sam-hash
        working-directory: ./${{ matrix.app }}
        run: |
          HASH=$(find . -type f -not -path "./.git/*" -not -path "./.github/*" -exec sha256sum {} \; | sort | sha256sum | cut -d' ' -f1)
          echo "sam_hash=$HASH" >> $GITHUB_OUTPUT

      # Get previous hash from SSM Parameter Store
      - name: Get previous hash
        id: previous-hash
        continue-on-error: true
        run: |
          PREV_HASH=$(aws ssm get-parameter --name "/${{ matrix.app }}/${{ matrix.environment }}/deployment-hash" --query "Parameter.Value" --output text || echo "none")
          echo "prev_hash=$PREV_HASH" >> $GITHUB_OUTPUT

      # sam build and deploy (only if hash changed)
      - name: Build and Deploy SAM application
        if: steps.previous-hash.outputs.prev_hash != steps.sam-hash.outputs.sam_hash
        working-directory: ./${{ matrix.app }}
        run: |
          # Build only if changes detected
          sam build --use-container
          
          # Delete stack if stuck in REVIEW_IN_PROGRESS
          aws cloudformation delete-stack --stack-name ${{ matrix.app }}-${{ matrix.environment }} || true
          aws cloudformation wait stack-delete-complete --stack-name ${{ matrix.app }}-${{ matrix.environment }} || true
          
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset \
            --stack-name ${{ matrix.app }}-${{ matrix.environment }} \
            --capabilities CAPABILITY_IAM \
            --region ap-southeast-1 \
            --parameter-overrides Environment=${{ matrix.environment }} Application=${{ matrix.app }} \
            --tags Application=${{ matrix.app }} Environment=${{ matrix.environment }} \
            --force-upload \
            --resolve-s3

      # Store new hash in SSM Parameter Store
      - name: Store new hash
        if: steps.previous-hash.outputs.prev_hash != steps.sam-hash.outputs.sam_hash
        run: |
          aws ssm put-parameter \
            --name "/${{ matrix.app }}/${{ matrix.environment }}/deployment-hash" \
            --value "${{ steps.sam-hash.outputs.sam_hash }}" \
            --type String \
            --overwrite